package com.livestrong.tracker.googlefitmodule.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fitnessDataDaoConfig;

    private final FitnessDataDao fitnessDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fitnessDataDaoConfig = daoConfigMap.get(FitnessDataDao.class).clone();
        fitnessDataDaoConfig.initIdentityScope(type);

        fitnessDataDao = new FitnessDataDao(fitnessDataDaoConfig, this);

        registerDao(FitnessData.class, fitnessDataDao);
    }
    
    public void clear() {
        fitnessDataDaoConfig.getIdentityScope().clear();
    }

    public FitnessDataDao getFitnessDataDao() {
        return fitnessDataDao;
    }

}
