package com.livestrong.tracker.googlefitmodule.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FITNESS_DATA".
 */
public class FitnessData {

    private Long id;
    private java.util.Date Date;
    private Integer Fitness_step_count;
    private Float FItness_distance;
    private Float Fitness_calorie_count;
    private java.util.Date Fitness_time;

    public FitnessData() {
    }

    public FitnessData(Long id) {
        this.id = id;
    }

    public FitnessData(Long id, java.util.Date Date, Integer Fitness_step_count, Float FItness_distance, Float Fitness_calorie_count, java.util.Date Fitness_time) {
        this.id = id;
        this.Date = Date;
        this.Fitness_step_count = Fitness_step_count;
        this.FItness_distance = FItness_distance;
        this.Fitness_calorie_count = Fitness_calorie_count;
        this.Fitness_time = Fitness_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public Integer getFitness_step_count() {
        return Fitness_step_count;
    }

    public void setFitness_step_count(Integer Fitness_step_count) {
        this.Fitness_step_count = Fitness_step_count;
    }

    public Float getFItness_distance() {
        return FItness_distance;
    }

    public void setFItness_distance(Float FItness_distance) {
        this.FItness_distance = FItness_distance;
    }

    public Float getFitness_calorie_count() {
        return Fitness_calorie_count;
    }

    public void setFitness_calorie_count(Float Fitness_calorie_count) {
        this.Fitness_calorie_count = Fitness_calorie_count;
    }

    public java.util.Date getFitness_time() {
        return Fitness_time;
    }

    public void setFitness_time(java.util.Date Fitness_time) {
        this.Fitness_time = Fitness_time;
    }

}
